---
- name: cisco create port_channel
  hosts: thirdteen
  gather_facts: no
  tasks:
  - name: channel-group 1-1
    ios_config:
      lines:
       - channel-group 1 mode active
      parents: interface gigabitEthernet 1/0/23

  - name: channel-group 1-2
    ios_config:
     lines:
      - channel-group 1 mode active
     parents: interface gigabitEthernet 1/0/24
