---
- name: 配置不同设备上不同端口的 VLAN
  hosts: switches
  gather_facts: no
  tasks:
    - name: 配置 VLAN
      ios_config:
        lines:
          - interface {{ item.interface }}
          - switchport access vlan {{ item.vlan_id }}
      delegate_to: "{{ inventory_hostname }}"
      when: item.hostname == inventory_hostname
      with_items: "{{ interfaces }}"
