---
- name: 配置不同设备上不同端口的 VLAN
  hosts: switches
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: 配置 VLAN
      ios_config:
        lines:
          - interface {{ item.interface }}
          - switchport access vlan {{ item.vlan_id }}
        parents: interface {{ item.interface }}
      delegate_to: "{{ inventory_hostname }}"
      with_items: "{{ interfaces }}"
